version: '3'
services:

  nginx :
    depends_on:
      - mariadb
      - wordpress
    build :
      context: ./requirements/Nginx
    image: nginx
    volumes:
      - worpress:/var/www/html/
    networks:
      - inception_network
    container_name : nginx
    ports:
      - "443:443"
    env_file: .env
    restart: unless-stopped

  wordpress:
    depends_on: 
      - mariadb
    build:
      context: ./requirements/WP
    image: wordpress
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception_network
    container_name: wordpress
    env_file: .env
    restart: unless-stopped

  mariadb :
    build: 
      context: ./requirements/MariaDB
      args: 
        WPDB_NAME: $MYSQL_DATABASE
        WPDB_USERNAME: $MYSQL_USER
        WPDB_PASS: $MYSQL_PASSWORD
    image: mariadb
    volumes: 
      - mariadb:/var/lib/mysql
    networks:
      - inception_network
    container_name: mariadb
    restart: unless-stopped


volumes:
  wordpress:
    driver: local
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/vducoulo/data/wordpress

  mariadb:
    driver: local
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/vducoulo/data/mariadb

networks:
  inception_network:
    driver: bridge
