version: '3'
services:

  inception_nginx :
    depends_on:
      - inception_mdb
      - inception_wp
    build :
      context: ./requirements/Nginx
    image: inception_nginx_img
    volumes:
      - inception_wp_content_vol:/var/www/html/
    networks:
      - inception_network
    container_name : inception_nginx
    ports:
      - "443:443"
    env_file: .env
    restart: unless-stopped

  inception_wp:
    depends_on: 
      - inception_mdb
    build:
      context: ./requirements/WP
    image: inception_wp_img
    volumes:
      - inception_wp_content_vol:/var/www/html/
    networks:
      - inception_network
    container_name: inception_wp
    env_file: .env

  inception_mdb :
    build: 
      context: ./requirements/MariaDB
      args: 
        WPDB_NAME: $MYSQL_DATABASE
        WPDB_USERNAME: $MYSQL_USER
        WPDB_PASS: $MYSQL_PASSWORD
    image: inception_mdb_img
    volumes: 
      - inception_mdb_db:/var/lib/mysql
    networks:
      - inception_network
    container_name: inception_mdb
    restart: unless-stopped


volumes:
  inception_wp_content_vol:
    driver: local
    name: inception_wp_content_vol
    driver_opts:
      type: none
      o: bind
      device: /Users/victorducoulombier/Documents/dev/42/inception_volumes_tmp/wordpress

  inception_mdb_db:
    driver: local
    name: inception_mdb_db
    driver_opts:
      type: none
      o: bind
      device: /Users/victorducoulombier/Documents/dev/42/inception_volumes_tmp/maria_db

networks:
  inception_network:
    driver: bridge