services:

  inception_nginx :
    build :
      context: ./srcs/nginx
    image: nginx
    volumes:
      - inception_wp_content_vol:/var/www/html/wordpress
    container_name : inception_nginx
    ports:
      - "443:443"
    env_file: .env

volumes:
  inception_wp_content_vol:

networks:
  default :
    name: inception_base_network