version: '3'
services:

  inception_nginx :
    depends_on:
      - inception_mdb
      - inception_wp
    build :
      context: ./srcs/nginx
    image: inception_nginx_img
    volumes:
      - inception_wp_content_vol:/var/www/html/
    container_name : inception_nginx
    ports:
      - "443:443"
    env_file: .env
    restart: unless-stopped

  inception_wp:
    depends_on: 
      - inception_mdb
    build:
      context: ./srcs/WP
    image: inception_wp_img
    volumes:
      - inception_wp_content_vol:/var/www/html/
    container_name: inception_wp
    env_file: .env

  inception_mdb :
    build: 
      context: ./srcs/mariadb
      args: 
        WPDB_NAME: $MYSQL_DATABASE
        WPDB_USERNAME: $MYSQL_USER
        WPDB_PASS: $MYSQL_PASSWORD
    image: inception_mdb_img
    volumes: 
      - inception_mdb_db:/var/lib/mysql
    container_name: inception_mdb
    restart: unless-stopped


volumes:
  inception_wp_content_vol:
  inception_mdb_db:

networks:
  default :
    name: inception_base_network